### ISSUE TITLE
no project license

### ISSUE THREAD

**Issue by substars** [omgtransit/omgtransit#3]
Pretty psyched about OSS OMG and would very much like to use and contribute to the project; any chance we could get a explicit OSS license to do so added? BSD 3-clause or MIT would seem like practical choices.

Thanks!

**Comment by wbushey** [comment]
On a related note, what is the IP on non-code, things like the logo/brand, copy, etc...?

**Comment by blackjk3** [comment]
@substars MIT was my first thought.  If you think that is a good idea i'll add the license file. The logo brand and copy were all created by the OMG team so I don't think there are any issues there.

**Comment by substars** [comment]
MIT would be great, all the freedom to tinker and then some :+1:

Brand/logo licensing is an interesting question but that can always be figured out later, as I don't believe MIT license says anything about trademark licensing et al. (note: IANAL)

**Comment by experimatt** [comment]
Late to respond here, but the logo/brand and copy are all good to be used in an open-source capacity
